# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  check-bats-version:
    name: Setup node
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build
      run:
        gcc main.c
        ./a.out
